import React from "react";
import {useEffect, useState} from 'react';
import type { NextPage } from "next";
import Head from "next/head";
import LayoutGuest from "../../components/templates/LayoutGuest";
import GuestCourseCard from "../../components/molecules/GuestCourseCard";
import Axios from 'axios'


//Number(localStorage.getItem("Course")

const course: NextPage = () => {
 var [courseArray,setCourseArray]=useState([]);

 function getCourses(x:Number){

    // Axios.post("http://localhost:8000/viewCourse",{id:Number(localStorage.getItem("CourseIIDD"))}

        Axios.post(`http://localhost:8000/viewCourse/${x}`

   ).then((response) => {
     setCourseArray(response.data[0])
     console.log(response.data)
     console.log(courseArray)
   }).catch((error) => console.log(error))
 }

  
 useEffect(() => {
  // if(localStorage.getItem("Course")!=undefined){
   var x = Number(localStorage.getItem("CourseID"));

  getCourses(x);
});

  return (
    <div className="bg-bc h-screen">
      <Head>
        <title>Course</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>

      <LayoutGuest>
        <div className="">
          <GuestCourseCard course={courseArray} />
        </div>
      </LayoutGuest>
    </div>
  );
};

export default course;
