import React from "react";
import {useEffect, useState} from 'react';
import type { NextPage } from "next";
import Head from "next/head";
import LayoutGuest from "../../components/templates/LayoutGuest";
import GuestCourseCard from "../../components/molecules/GuestCourseCard";
import Axios from 'axios'
import {useParams} from 'react-router-dom'


//Number(localStorage.getItem("Course")

const course: NextPage = () => {
  var [Course  , setCourse] = useState('');
 // localStorage.setItem("isCorp","1")
  function guestViewCourse(){
    Axios.post("http://localhost:8000/viewCourse", {id: 1}).then((response)=>{
      setCourse(response.data)
      console.log(Course);


      
    })
      .catch(error=>console.error("there is an error"))
  }
  useEffect(() => {guestViewCourse()})
    

  return (
    <div className="bg-bc h-screen">
      <Head>
        <title>View Course</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LayoutGuest>
        <div className="">
          <GuestCourseCard course={Course} />
        </div>
      </LayoutGuest>
    </div>
  );
};

export default course;
