import React, { useEffect, useMemo } from "react";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import LayoutGuest from "../../components/templates/LayoutGuest";
import GuestCourses from "../../components/molecules/GuestCourses";
import HeaderGuest from "../../components/organisms/HeaderGuest";
import {useState} from 'react';
import axios from 'axios';


const guestcourses: NextPage = () => {
  var [CourseArray,setCourseArray]=useState([]);
  function getCourses(){
     axios.get("http://localhost:8000/viewCoursesALL"
    ).then((response) => {
      console.log("Hello")
      console.log(response.data)
      setCourseArray(response.data)
    }).catch((error) => console.log(error))
  }
  var x =useEffect(() =>{getCourses()},[])

  return (
    <div className="bg-bc h-screen">
      <Head>
        <title>Courses</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutGuest>
        <div>

            <HeaderGuest/>
          <GuestCourses courses={CourseArray}/>
        </div>
      </LayoutGuest>
      
    </div>
  );
};

export default guestcourses;
