import React from "react";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import LayoutGuest from "../../components/templates/LayoutGuest";
import GuestCourses from "../../components/molecules/GuestCourses";



const guestcourses: NextPage = () => {
  return (
    <div className="bg-bc h-screen">
      <Head>
        <title>Courses</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutGuest>
        <div>
            
          <GuestCourses courses={{}}/>
        
        </div>
      </LayoutGuest>
      
    </div>
  );
};

export default guestcourses;
