import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Layout from "../components/templates/Layout";
import Nav from "../components/atoms/Nav";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";

const home: NextPage = () => {
  const router = useRouter();
     
  useEffect(() => {
    router.push("/guest/login")
  });
  return (
    <div className="flex flex-col bg-[url('/images/bgacl.jpeg')] w-full h-screen bg-cover">
      <Head>
        <title>Fogration</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <Nav links={[]} />
   

        <div className="flex flex-col justify-start items-start bg-white opacity-50  h-[calc(100vh-64px)] w-1/2">
          <h1 className="text-2xl font-bold text-lachmara">
            Welcome to Fogration
          </h1>
        </div>
    </div>
  );
};

export default home;
