import React from "react";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Layout from "../../components/templates/Layout";
import CoursesCard from "../../components/molecules/CoursesCard";


const courses: NextPage = () => {
  return (
    <div className={""}>
      <Head>
        <title>Courses</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div>
          <CoursesCard />
        </div>
      </Layout>
    </div>
  );
};

export default courses;
