import React, { useEffect, useState } from "react";
import Layout from "../../components/templates/Layout";
import type { NextPage } from "next";
import Head from "next/head";
import UserCoursesCard from "../../components/molecules/UserCoursesCard";
import HeaderUserCourses from "../../components/organisms/HeaderUserCourses";
import axios from "axios";


const courses: NextPage = () => {
  var [CourseArray,setCourseArray]=useState([]);
  const [isCorporate, setIsCorporate]= useState("false");

  useEffect(() => {
    setIsCorporate(localStorage.getItem("isCorp"))
  })

  

  function getCourses(){
      if(localStorage.getItem("isCorp")=="true"){
        axios.get("http://localhost:8000/viewCoursesCorporate"
       ).then((response) => {
         console.log(Number(localStorage.getItem("user_id")))
   
         setCourseArray(response.data)
       }).catch((error) => console.log(error))
     }
   else{
       axios.get("http://localhost:8000/viewCoursesALL"
      ).then((response) => {
        console.log(Number(localStorage.getItem("user_id")))
   
        setCourseArray(response.data)
      }).catch((error) => console.log(error))
    }
   }
  

  var x =useEffect(() =>{getCourses()},[])



  return (
    <div className="bg-bc h-screen">
      <Head>
        <title>Courses</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div>
          <HeaderUserCourses/>
          <UserCoursesCard courses={CourseArray}/>
        </div>
      </Layout>
    </div>
  );
};



export default courses;
