import React, { useEffect, useState } from "react";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Layout from "../../components/templates/Layout";
import { useRouter } from "next/router";
import { Doughnut } from "react-chartjs-2";
import {Chart, ArcElement} from 'chart.js'
import LinearProgress from '@mui/joy/LinearProgress';
import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem';
import ListItemButton from '@mui/material/ListItemButton';
import ListItemIcon from '@mui/material/ListItemIcon';
import ListItemText from '@mui/material/ListItemText';
import Checkbox from '@mui/material/Checkbox';
import IconButton from '@mui/material/IconButton';
import CommentIcon from '@mui/icons-material/Comment';

import { Box, CircularProgress, CircularProgressProps, Typography } from "@mui/material";
import { pink } from "@mui/material/colors";
import Link from "next/link";
import { BsGithub } from "react-icons/bs";
Chart.register(ArcElement);
function CircularProgressWithLabel(
  props: CircularProgressProps & { value: number },
) {
  return (
    <Box sx={{ position: 'relative', display: 'inline-flex' }}>
      <CircularProgress variant="determinate" {...props} size={100}/>
      <Box
        sx={{
          top: 0,
          left: 0,
          bottom: 0,
          right: 0,
          position: 'absolute',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
         
          
          
        }}
      >
        <Typography
          variant="caption"
          component="div"
          color="white"
        >{`${Math.round(props.value)}%`}</Typography>
      </Box>
    </Box>
  );
}
const dashboard: NextPage = () => {
   const [checked, setChecked] = React.useState([0]);

  const handleToggle = (value: number) => () => {
    const currentIndex = checked.indexOf(value);
    const newChecked = [...checked];

    if (currentIndex === -1) {
      newChecked.push(value);
    } else {
      newChecked.splice(currentIndex, 1);
    }

    setChecked(newChecked);
  };
  const courses = [
    {
      id: 1,
      name: "Introduction to Python",
      progress : 90,
      exams: [
        {
          id: 1,
          name: "Exam 1",
          progress: 50,
        },
        {
          id: 2,
          name: "Exam 2",
          progress: 78,
        },
        {
          id: 3,
          name: "Exam 3",
          progress: 50,
        },
        {
          id: 4,
          name: "Exam 4",
          progress: 99,
        },
        {
          id: 5,
          name: "Exam 5",
          progress: 10,
        },
        
      ],}
      ,
    {
      id: 2,
      name: "Introduction to Java",
      progress : 50,
      exams: [
        {
          id: 1,
          name: "Exam 1",
          progress: 20,
        },
        {
          id: 2,
          name: "Exam 2",
          progress: 50,
        },
        {
          id: 3,
          name: "Exam 3",
          progress: 78,
        },
        {
          id: 4,
          name: "Exam 4",
          progress: 100,
        },
        {
          id: 5,
          name: "Exam 5",
          progress: 50,
        },
       
      ],
    }
    ]

  
  const headers = ["Song", "Artist", "Year"];
  const router = useRouter();

  var authBool=false;
 function Auth(){
   localStorage.clear();
   localStorage.setItem("Login","false");
   localStorage.setItem("Type","");
   router.push("/guest/login");

 }
 const[Type,setType] = useState("User");
 useEffect(()=>{
  if(authBool==true){
    Auth();
  }
  else{
    setType(localStorage.getItem("Type"));}});
  if(Type!="User" && Type!="Corp"){
    authBool=true;
   }
 else{
 
  return (
    <div className="flex flex-col justify-between bg-bc w-full h-screen bg-cover">
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon 1.ico" />
      </Head>

      <Layout>
        <div className="flex flex-col">
          <div className=" p-2 m-5  rounded-md flex flex-col gap-2">

            <div className="flex flex-row gap-2">
              {courses.map((course,index) => (
                <div key={index} className="bg-black3 flex justify-start items-start flex-col rounded-lg p-2 w-72 m-2">
                  <p className="text-white text-xl">{course.name}</p>
                  {/* {
                    course.progress==100?
                    <p className="text-white text-xl">Completed</p>
                    :
                    <p className="text-white text-xl">In progress</p>

                  } */}
                  <div className="text-white ">Progress</div>
                  <div className="bg-black3 flex justify-center items-center flex-col rounded-lg w-52 p-5">
                    <CircularProgressWithLabel variant="determinate" color="secondary" value={course.progress} />
                  </div>
                  <div className="text-white ">Grades</div>
                  
                  <div>
                    {
                      (course.exams).map((exam,index)=>(
                        <div key={index} className="bg-black3 flex justify-start items-start flex-col rounded-lg ">
                          <p className="text-white">{exam.name}</p>
                          
                          <div className="flex flex-row ">
                        <LinearProgress
                      className=" bg-black2 w-24 text-white m-2 "
                      thickness={7}
                      determinate 
                        variant="outlined"
                        value={exam.progress}
                        >
                        
                        </LinearProgress>
                        <Typography className="text-white text-sm"
                      >
                      {exam.progress}%
                      </Typography>
                        </div>
                        </div>))
                    }
                 
                  </div>
                </div>
              ))}

<List  className="bg-black3 rounded-md p-2 m-2" sx={{ width: '100%', maxWidth: 360, bgcolor: '' } }>
      {[0, 1, 2, 3].map((value) => {
        const labelId = `checkbox-list-label-${value}`;

        return (
          <ListItem
            key={value}
            className="text-white bg-black3 rounded-md"
           
            disablePadding
          >
            <ListItemButton role={undefined} onClick={handleToggle(value)} dense>
              <ListItemIcon>
                <Checkbox
                  edge="start"
                  checked={checked.indexOf(value) !== -1}
                  tabIndex={-1}
                  disableRipple
                  inputProps={{ 'aria-labelledby': labelId }}
                  color="default"
                  
                />
              </ListItemIcon>
              <ListItemText id={labelId} primary={`Finish course ${value + 1}`} />

            </ListItemButton>
          </ListItem>
        );
      })}
    </List>

          </div>
          <div>

          </div>



       
        
         
    </div>
     </div>
      </Layout>

 <div className="flex items-center bg-bc  bg-cover text-gray-200 flex-col px-6 ">
         
          <div className="border-t border-gray-500 w-11/12">
          </div>
          <div className="flex flex-row  justify-between w-full items-center">
          <h1 className="text-sm ">
             @2022 Fogration Team.All Rights Reserved
          </h1>
           <div className="flex flex-row gap-2 ">
          <Link href="" className="text-gray-300 hover:underline" >About us</Link>
          <Link href="/guest/policies" className="text-gray-300 hover:underline" >Payment</Link>
           <Link href="/guest/policies" className="text-gray-300 hover:underline" >Refund policy</Link>
           <Link href="/guest/policies" className="text-gray-300 hover:underline" >Terms of service</Link>
          </div>

          <Link href="https://github.com/Andysm21/ACL_Fogration_FE/blob/main/README.md">
          <BsGithub size={30}  className="text-white hover:cursor-pointer"/>
          </Link>
          </div>
        </div>
      
    </div>

  );
};
}
export default dashboard;
