import React, { useEffect, useState } from "react";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Layout from "../../components/templates/Layout";
import { useRouter } from "next/router";

const dashboard: NextPage = () => {
  const headers = ["Song", "Artist", "Year"];
  const router = useRouter();

  var authBool=false;
 function Auth(){
   localStorage.clear();
   localStorage.setItem("Login","false");
   localStorage.setItem("Type","");
   router.push("/guest/login");

 }
 const[Type,setType] = useState("User");
 useEffect(()=>{
  if(authBool==true){
    Auth();
  }
  else{
    setType(localStorage.getItem("Type"));}});
  if(Type!="User" && Type!="Corp"){
    authBool=true;
   }
 else{
 
  return (
    <div className="flex flex-col bg-bc w-full h-screen bg-cover">
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon 1.ico" />
      </Head>

      <Layout>
        <div></div>
      </Layout>
    </div>
  );
};
}
export default dashboard;
