import React, {useEffect, useState} from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../../components/templates/Layout";
import UserCourseCard from "../../components/molecules/UserCourseCard";
import ViewInstructor from "../../components/molecules/ViewInstructor";
import axios from 'axios';

//        <ViewInstructor user={ personArray} />

const instructor: NextPage = () => {

  var [personArray, setpersonArray] = useState({});

  useEffect(() => {
    console.log("Heyyy");
    getInstructor();
    console.log(personArray);
  }, )

  function getInstructor(){
    axios.post("http://localhost:8000/instructorAccount", {Instructor_ID: Number(localStorage.getItem("course_instructor"))}).then((response) => {
  setpersonArray(response.data);
 
}).catch((error) => console.log(error))
}

  return (
    <div className="bg-bc h-screen">
      <Head>
        <title>View Course</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
      <div className="">
          <ViewInstructor user={personArray} />
        </div>
      </Layout>
    </div>
  );
};
export default instructor;
