import React, {useEffect, useState} from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../../components/templates/Layout";
import UserCourseCard from "../../components/molecules/UserCourseCard";
import ViewInstructor from "../../components/molecules/ViewInstructor";
import axios from 'axios';
import { useRouter } from "next/router";

//        <ViewInstructor user={ personArray} />

const instructor: NextPage = () => {

  var [personArray, setpersonArray] = useState({});

  useEffect(() => {
    console.log("Heyyy");
    getInstructor();
    console.log(personArray);
  }, )

  function getInstructor(){
    axios.post("http://localhost:8000/instructorAccount", {Instructor_ID: Number(localStorage.getItem("course_instructor"))}).then((response) => {
  setpersonArray(response.data);
 
}).catch((error) => console.log(error))
}
const router = useRouter();

var authBool=false;
function Auth(){
 localStorage.clear();
 localStorage.setItem("Login","false");
 localStorage.setItem("Type","");
 router.push("/guest/login");

}
const[Type,setType] = useState("User");
useEffect(()=>{
if(authBool==true){
  Auth();
}
else{
  setType(localStorage.getItem("Type"));}});
if(Type!="User" && Type!="Corp"){
  authBool=true;
 }
else{

  return (
    <div className="bg-bc h-screen">
      <Head>
        <title>Instructor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon 1.ico" />
      </Head>
      <Layout>
      <div className="">
          <ViewInstructor user={personArray} />
        </div>
      </Layout>
    </div>
  );
}
};
export default instructor;
