import React from "react";
import Layout from "../../components/templates/Layout";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
// interface Props {
//   data: {
//     song: string;
//     artist: string;
//     year: string;
//   }[];
// }

const person = {
  _id: {
    $oid: "636880e12886948f062b493e",
  },
  User_ID: 4,
  User_Name: "Pasha",
  User_Email: "Pasha@gmail.com",
  User_Password: "1234",
  User_Role: "Student",
  User_Country: "Egypt",
  User_City: "Berlin",
  User_Address: "ALexanderplatz",
  User_Courses: [
    {
      _id: {
        $oid: "666820e1288794o098062b493e",
      },
      Course_ID: 4,
      Course_Title: "asda",
      Course_Subject: "Computer Science",
      Course_Description: "Data Structures and Algorithms",
      Course_Price: 0,
      Course_Rating: 5,
      Course_Instructor: "Malak",
      Course_Hours: 5,
      Course_Country: "Egypt",
      Course_Discount: 10,
      Course_Discount_Duration: 5,
      Course_Subtitle: [
        {
          Subtitle_ID: 1,
          Subtitle_Name: "S1",
          Subtitle_Course_ID: "1",
          Subtitle_Video: [
            {
              Video_ID: 1,
              Video_Link:
                "https://www.youtube.com/watch?v=Q8TXgCzxEnw&list=PL9gnSGHSqcnr_DxHsP7AW9ftq0AtAyYqJ&index=2",
              Video_Subtitle: "S1",
              Video_Description: "Introduction",
              Video_Length: 10,
            },
          ],
          Subtitle_Hours: "10",
        },
        {
          Subtitle_ID: 2,
          Subtitle_Name: "S2",
          Subtitle_Course_ID: "1",
          Subtitle_Video: [
            {
              Video_ID: 1,
              Video_Link:
                "https://www.youtube.com/watch?v=Q8TXgCzxEnw&list=PL9gnSGHSqcnr_DxHsP7AW9ftq0AtAyYqJ&index=2",
              Video_Subtitle: "S1",
              Video_Description: "Introduction",
              Video_Length: 10,
            },
          ],
          Subtitle_Hours: "10",
        },
      ],
      Course_Trainee: [{ Trainee_ID: 1, Trainee_Name: "Ahmed" }],
      Course_Review: ["Very Good Course"],
      Course_Rate: ["zeft"],
      Course_Exam: [
        { Exam_ID: "1", Exam_Question_ID: ["1", "2"], Exam_Grade: "A" },
      ],
    },
  ],
};

const profile: NextPage = () => {
  return (
    <div className="bg-bc h-screen">
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div></div>
      </Layout>
    </div>
  );
};

// export const getServerSideProps: GetServerSideProps<Props> = async (ctx) => {
//   const data = [
//     {
//       song: 'The Sliding',
//       artist: 'The Beatles',
//       year: '1967',
//     },
//     {
//       song: 'Witchy Woman',
//       artist: 'The Beatles',
//       year: '1967',
//     },
//   ];

//   return {
//     props: {
//       data,
//     },
//   };
// };

export default profile;
