import React, { useEffect, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../../components/templates/Layout";
import UserMyCourseCard from "../../components/molecules/UserMyCourseCard";
import  axios  from "axios";


const viewmycourse: NextPage = () => {
  var [courseArray,setCourseArray]=useState([]);
  var type;

  function getCourses(){
 
    var userid= Number(localStorage.getItem("user_id"));

    if(localStorage.getItem("Type")=="Corp"){
      type=2;
    }
    else if(localStorage.getItem("Type")=="User"){
      type=1;
    }
    // Axios.post("http://localhost:8000/viewCourse",{id:Number(localStorage.getItem("CourseIIDD"))}
     var x = Number(localStorage.getItem("CourseID"));
    console.log(x);
    axios.post(`http://localhost:8000/viewMyCourse/${x}`,{id:x,UserID:userid,type:type}

   ).then((response) => {
     setCourseArray(response.data)
     console.log(response.data)
     console.log(courseArray)
   }).catch((error) => console.log(error))
 }
 
   
  useEffect(() => {
   // if(localStorage.getItem("Course")!=undefined){
   getCourses();
   console.log(courseArray)
 }, []);
  
  return (
    <div className="bg-bc h-screen">
      <Head>
        <title>View Course</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="">
          <UserMyCourseCard course={courseArray} />
        </div>
      </Layout>
    </div>
  );
};
export default viewmycourse;
