import React, { useEffect, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../../components/templates/Layout";
import UserMyCourseCard from "../../components/molecules/UserMyCourseCard";
import  Axios  from "axios";


const viewmycourse: NextPage = () => {
  var [course,setCourseArray]=useState([]);


  function getCourses(){

    if(localStorage.getItem("isCorp")){
    // Axios.post("http://localhost:8000/viewCourse",{id:Number(localStorage.getItem("CourseIIDD"))}
        Axios.post(`http://localhost:8000/myCoursesCorp/`

   ).then((response) => {
     console.log(response.data);
     setCourseArray(response.data[0])
     console.log(response.data)
     console.log(course)
   }).catch((error) => console.log(error))
 }
//  else{
//   Axios.post(`http://localhost:8000/myCoursesInd/`

//   ).then((response) => {
//     console.log(response.data[0]);
//     setCourseArray(response.data[0])
//     console.log(response.data)
//     console.log(course)
//   }).catch((error) => console.log(error))
//   }
 }

  
useEffect(()=>{
  getCourses();
})
  
  return (
    <div className="bg-bc h-screen">
      <Head>
        <title>View Course</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="">
          <UserMyCourseCard course={course} />
        </div>
      </Layout>
    </div>
  );
};
export default viewmycourse;
