import React, { useEffect, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../../components/templates/Layout";
import UserCourseCard from "../../components/molecules/UserCourseCard";
import axios from "axios";



const viewcourse: NextPage = () => {
  var [courseArray,setCourseArray] = useState([]);

  function getCourses(){
 
    // Axios.post("http://localhost:8000/viewCourse",{id:Number(localStorage.getItem("CourseIIDD"))}
     var x = Number(localStorage.getItem("CourseID"));

        axios.post(`http://localhost:8000/viewCourse/${x}`

   ).then((response) => {
     setCourseArray(response.data)
     console.log(response.data)
     console.log(courseArray)
   }).catch((error) => console.log(error))
 }

  useEffect(()=>{
getCourses();
  })
  return (
    <div className="bg-bc h-screen">
      <Head>
        <title>View Course</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="">
          <UserCourseCard course={courseArray} />
        </div>
      </Layout>
    </div>
  );
};
export default viewcourse;
