import React, { useEffect, useState } from "react";
import type {  NextPage } from "next";
import Head from "next/head";
import Layout from "../../components/templates/Layout";
import HeaderAdminCourses from "../../components/organisms/HeaderAdminCourses";
import AdminCoursesCard from "../../components/molecules/AdminCoursesCard";
import axios from "axios";



const courses: NextPage = () => {
  var [coursesArray,setCourseArray]=useState([]);

  function getCourses(){
    axios.get("http://localhost:8000/viewCoursesALL"
   ).then((response) => {
     setCourseArray(response.data)
     // console.log(response.data)

   }).catch((error) => console.log(error))
 }
 function getCoursesSearch(){
  axios.post("http://localhost:8000/Search",{
    searchR: localStorage.getItem("Search")
  }
 ).then((response) => {
   //console.log("Function:")
   // console.log(localStorage.getItem("Search"))
   // console.log("response data:")
   if(response.data == "")
    setCourseArray([])
   else
    setCourseArray(response.data)

 }).catch((error) => console.log(error))
}

useEffect(()=>{
  // console.log(localStorage.getItem("Subject"))  
        if(localStorage.getItem("Search")=='' || localStorage.getItem("Search")==""){

         getCourses()
         localStorage.setItem("Search","")

        //  console.log("Hi")
        }
        else{
          getCoursesSearch();
        

    }
})

  return (
    <div className="bg-bc h-screen">
      <Head>
        <title>Courses</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div>
        <HeaderAdminCourses courses={coursesArray}/>
        <AdminCoursesCard courses={coursesArray} />
        </div>
      </Layout>
    </div>
  );
};

export default courses;
