import React, { useEffect, useState } from "react";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Layout from "../../components/templates/Layout";
import UsersAdditions from "../../components/organisms/UsersAdditions";

const dashboard: NextPage = () => {
  const headers = ["Song", "Artist", "Year"];

  return (
    <div className="bg-bc h-screen">
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div>
          <UsersAdditions/>

        </div>
        <div></div>
      </Layout>
    </div>
  );
};

export default dashboard;
