import React, { useEffect, useState } from "react";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Layout from "../../components/templates/Layout";
import UsersAdditions from "../../components/organisms/UsersAdditions";
import { useRouter } from "next/router";

const dashboard: NextPage = () => {
  const headers = ["Song", "Artist", "Year"];
  const router = useRouter();


 var authBool=false;
 function Auth(){
   localStorage.clear();
   localStorage.setItem("Login","false");
   localStorage.setItem("Type","");
   router.push("/guest/login");

 }
 const[Type,setType] = useState("Admin");
 useEffect(()=>{
  if(authBool==true){
    Auth();
  }
  else{
    setType(localStorage.getItem("Type"));
  }
});
console.log(Type);
  if(Type!="Admin"){
    authBool=true;
   }
 else{
  return (
    <div className="bg-bc h-screen">
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div>
          <UsersAdditions/>

        </div>
        <div></div>
      </Layout>
    </div>
  );
};
}
export default dashboard;
